baseURL = 'https://bananegame.github.io/'
languageCode = 'en-us'
title = 'Banane, le jeu'
theme = "banane"
  [params]
    custom_css = ["custom.css"]

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"